### ISSUE TITLE
Add GitHub Actions reformatter

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#98] opened 2019-09-13 06:46 UTC
I want to remove the clang-format check. It has caused me only trouble and it is annoying to see a change fail just because the format check thinks some headers should be ordered slightly differently.

Automation should save time, and so far this is only causing an annoyance.

**Comment by HDembinski** [comment] 2019-09-13 08:13
I am not willing to accept a solution which requires me and other potential developer to install docker to produce consistent formatting. This is an unacceptable threshold for contributing.

**Comment by HDembinski** [comment] 2019-09-13 08:20
I think it is acceptance to ask people to install clang-format-8 and use the .clang-format file in their editor. This is what I did. Apparently, there are still formatting differences between my machine and the clang-format check.

I am extremely annoyed by this. White space is not so relevant that it justifies causing so much trouble.

**Comment by henryiii** [comment] 2019-09-13 22:16
You do not need Docker. You need the `-sort-includes` flag. Clang format by default tries not to break code.

If you don’t like the check, leave the x red, Azure makes this very clear that it is the format check that failed (and I’ll pull, reformat, and push, just as you already made me do). I have done this very successfully with many contributions to CLI11. It does not impair contributions, rather it encourages them. Or write a bot that will reformat for you, like CMake uses. Maybe GitHub Actions will make this easier? Or argue that we should drop sorting, but I like it because it forces nice clear grouping for the cases where order matters, and sometimes finds bugs where the order matters when it shouldn't. But do not kill the whole check!

Proper, reproducible white space males merge conflicts easier, make code easier to read, and speeds up development by not allowing the programmer to chose or change formatting. Most large software I know of that does not have a formatting requirement is trying to add one after years of dev and it’s hard (LHCb, Blender).

Also, *never* assume developers will do anything. That’s why we have CI. I don’t always use an editor that supports auto formatting, for example. Like Xcode or GitHub online.

I take it you are going to hate me when I add a clang-tidy check too...

**Comment by henryiii** [comment] 2019-09-13 22:19
Just run the format in the scripts directory that does not have docker in the name. Or fix your editor. Or get in the habit of sorting your includes (`:sort` in VI on a selection).

If I add a new include and you add a new include, if they are the same include and are sorted, there will not be a merge conflict.

**Comment by HDembinski** [comment] 2019-09-16 13:15
I was not aware that my clang-format does not sort the headers. I thought it does. I also like sorted headers, this is not the issue. The issue is that a PR should not fail on the grounds of whitespace. Whitespace is not cosmetic.

I would be ok with a bot that regularly corrects the white-space of the project once a day, or something that automatically applies clang-format to each PR, but I don't know how to set that up. 

I am much less against a clang-tidy check, because that may actually find code smells and bugs, so it is a different thing.

**Comment by HDembinski** [comment] 2019-09-16 13:21
A clang-format check is not doing anything useful in my view and it makes it harder for me to contribute to this project. It is a waste to trigger all Azure checks just to get some failing format check passing.

**Comment by henryiii** [comment] 2019-09-16 15:59
Cmake is the only project I know that does the auto-formatting bot, but it's a custom gitlab instance. Maybe GitHub actions will make this easier? Also, you should still (and this is the way they do it) have a check that fails, *then* an *optional* way to trigger the reformat - you should never rewrite git comments without a way to avoid it. (PS: It's quite nice, it actually rewrites all commits in the PR so all of them pass independently).

The clang-format test keeps the code clean and makes sure everything committed doesn't later trigger a reformat (and therefore break `git blame`), so l think it is very useful. If devs (like you) use clang-format in their editors, they won't trigger this as false. And it is quite clear if only formatting fails, it is listed separately on the GitHub PR. And if you don't like it failing, the solution is not to remove it, but to fix the failure!

**Comment by henryiii** [comment] 2019-09-16 16:42
A PR should fail if it's not ready to merge.  A poorly formatted PR is not ready to merge.

**Comment by henryiii** [comment] 2019-09-16 18:00
Something like this would be doable, I think, in GitHub Actions: https://github.com/peter-evans/autopep8 . It looks like we now have the GitHub Actions beta enabled for Scikit-HEP, too.

**Comment by henryiii** [comment] 2019-09-16 18:03
This one might be a bit more automatic: https://github.com/MarvinJWendt/run-node-formatter 

In either case, someone would need to write one to do it with clang-format (I might eventually).

**Comment by HDembinski** [comment] 2019-09-17 08:51
> A PR should fail if it's not ready to merge. A poorly formatted PR is not ready to merge.

We don't need a clang-format test between us. For another contributor, we would anyway review their patch. It doesn't matter whether that guy is using clang-format, as long as the patch is readable. A patch does not get more readable by having headers in alphabetical format. This seems pedantic instead of practical.

**Comment by HDembinski** [comment] 2019-09-17 08:54
If the formatting can be done with Github actions centrally then that would be perfect.

**Comment by henryiii** [comment] 2019-09-17 14:42
> We don't need a clang-format test between us.

Yes, I do, even if I'm the only developer. I don't always remember to format; I work in different editors and on different computers. And for someone else's patch, it's extra trouble for me to download and run the formatting check when the CI could do it for me and save time.

I told you, while patches do not get more readable by being in alphabetical format, *it reduces merge conflicts*, which is a very good thing. If two people add the same header, it's not a merge conflict if they are in the same place, which alphabetical ordering helps.

If you don't like the red X by the format job, *just ignore it*. That's why they are all listed separately on the PR page. (But I prefer to fix it, so please let me fix it if you don't want to).

At some point, we can work on GitHub Actions, and then it will be even easier to fix.

**Comment by henryiii** [comment] 2019-11-26 21:40
Currently this is only available for private repositories; I expect you could pretty easily make it secure for local branches of public repositories, but not (currently) for PRs.

See repo readme and issue https://github.com/pre-commit/action/issues/1 for more info.

**Comment by henryiii** [comment] 2021-03-09 19:34
This is done now. clang-format is not available on pre-commit.ci, but the rest now gets checked and auto-fixed. clang-format checks are still run, but sadly can't be auto-fixed yet.

**Closed as completed by henryiii** 2021-03-09 19:34 UTC
Labels: enhancement
